### PR TITLE
[Feature] Added Shimmer Loading

### PR DESCRIPTION
**Pull request by veerprakash28**
What does this PR do?
Added Shimmer UI for Banner and Images Card

Related Issue(s)
Related Issue: https://github.com/Vijaykv5/Image-Searcher/issues/43
Related PR: PR #82
Related PR: PR #55 

Changes

Added Shimmer Loading Component for Image card and Banner
Prettify Code
Removed Extra Download function code

### CODE REVIEW

**Comment by Vijaykv5** [comment]
@veerprakash28 May you add a video regarding the PR please

**Comment by veerprakash28** [comment]
Uploading screen-recording-2023-10-03-at-123103-am_ymdM78X0.mp4…

@Vijaykv5 added

**Comment by veerprakash28** [comment]
https://github.com/Vijaykv5/SnapGrid/assets/94482800/e0290d1b-678b-488c-8e8e-34d43821d3c1

@Vijaykv5 added

**Comment by Vijaykv5** [comment]
Thanks for contributing 🚀

**Pull request merged**
