### PR TITLE
Created the signup page ui

### LINKED ISSUE #162: [FEATURE] Build sign up page
**Description**

When a user clicks the sign-up button, a sign-up page must occur, maybe authentication will be added in the future. Please assign me to work on this.

### PR DESCRIPTION
**Pull request by aasimtaif**
**What does this PR do?**
I have created a responsive signup page. It is just UI that takes the name, email & password  with no authentication functionality, If you want  authentication  I can do it 

**Related Issue(s)**
fixes #162 

**Changes**
Now If you click on the signup button on the home page it will take you to the signup page 

**Screenshots or GIFs (if applicable)**
Screenshot from 2023-10-23 22-10-17

**Checklist**
- [x] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [x] My code follows the project's coding style and conventions.
- [ ] I have added unit tests (if applicable) to ensure the code works as expected.
- [ ] I have updated the project documentation (if necessary).

**Additional Comments**
Add any additional comments, context, or information about this PR.

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Vijaykv5** [comment]
This Isuue has being already being assigned by someone ...Please Don't work on Unassigned issues

**Comment by aasimtaif** [comment]
> This Issue has being already being assigned by someone ...Please Don't work on Unassigned issues

Yes I know but it was a week ago and he didn't raise a  PR .That's why I did this

**Comment by Vijaykv5** [comment]
If he didn't responded or not willing to work, I'll reconsider your case and open the PR and will merge it mate :)

**Comment by Vijaykv5** [comment]
@aasimtaif would be much appreciated if you can add a star to this project 🙂

**Comment by Mayank-Sharma17** [comment]
great work @aasimtaif, @Vijaykv5 you can merge his PR ✅.

**Comment by aasimtaif** [comment]
> If he didn't responded or not willing to work, I'll reconsider your case and open the PR and will merge it mate :)
Can you merge my PR @Mayank-Sharma17 approved it

**Comment by Vijaykv5** [comment]
@aasimtaif may you can add a Video on how exactly the Sign up page works ...and please show its responsive too :)

**Comment by aasimtaif** [comment]
[Tab-1698214678302.webm](https://github.com/Vijaykv5/SnapGrid/assets/83891519/26125688-10fd-4b51-8d9e-71173afff22d)
As of now, the form doesn't do anything as you just asked for a UI.But if you want full auth functionality i can do if

**Comment by Vijaykv5** [comment]
> [Tab-1698214678302.webm](https://github.com/Vijaykv5/SnapGrid/assets/83891519/26125688-10fd-4b51-8d9e-71173afff22d) As of now, the form doesn't do anything as you just asked for a UI.But if you want full auth functionality i can do if

I think we can add Auth functionality on new PR later
Could you add Login also , when user clicks on it, it much change to login screen

**Comment by aasimtaif** [comment]
> > [Tab-1698214678302.webm](https://github.com/Vijaykv5/SnapGrid/assets/83891519/26125688-10fd-4b51-8d9e-71173afff22d) As of now, the form doesn't do anything as you just asked for a UI.But if you want full auth functionality i can do if
> 
> I think we can add Auth functionality on new PR later Could you add Login also , when user clicks on it, it much change to login screen

Yes on it

**Pull request closed without merging**
