### PR TITLE
Fix redirect rule netlify

### LINKED ISSUE #144: [BUG] Missing configuration redirect rule for your site
**Description**
When I refresh the page https://snapgrid.netlify.app/search, the page is not found from netlify.

**Expected Behavior**
When I refresh the page https://snapgrid.netlify.app/search, it should return the page https://snapgrid.netlify.app/search

**Actual Behavior**
When refreshing the page https://snapgrid.netlify.app/search, it becomes not found page

**Screenshots (if applicable)**
https://github.com/Vijaykv5/SnapGrid/assets/51848196/8e639b65-a7b3-4743-850d-b9f03318a311

**Additional Information**
Hi Sir @Vijaykv5 
I'm new to open source contributions and I'd really want to contribute to your project! Can you please assign this issue to me? Thank you for your response Sir @Vijaykv5 . I also participated in Hacktoberfest2023.

### PR DESCRIPTION
**Pull request by rhnas110**
**What does this PR do?**
Create redirect rule netlify for react-router

**Related Issue(s)**
Fixes #144 

**Changes**
Add file netlify.toml for redirect rule router

**Screenshots or GIFs (if applicable)**
image
Result:
https://github.com/Vijaykv5/SnapGrid/assets/51848196/1b0834e0-9a41-43d3-aa62-5b7d79e7864e

**Checklist**
- [x] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [x] My code follows the project's coding style and conventions.
- [ ] I have added unit tests (if applicable) to ensure the code works as expected.
- [ ] I have updated the project documentation (if necessary).

**Additional Comments**
Thank you for your response Sir @Vijaykv5 , and giving this task to me, I'm enjoyed to do it especially I can contribute to your project Sir @Vijaykv5 .

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Vijaykv5** [comment]
@rhnas110  but why its not showing the images.

The search image is not yet displayed

**Comment by rhnas110** [comment]
When I open the console, function call API from unsplash it's error, because client_id is undefined Sir, I think it's because only netlify preview can't read env. and I see for query params client_id value from env, I guess that's the cause Sir.

Here from console.log
image

And this is from unsplash API call (it says client_id undefined)
image

**Comment by Vijaykv5** [comment]
cool @rhnas110. I think it works in live deploy.
Thanks for your contribution

**Comment by rhnas110** [comment]
Same here Sir @Vijaykv5 , I'm glad I could contribute to your project.

**Pull request merged**
