### PR TITLE
Feature/drag and drop

### PR DESCRIPTION
**Pull request by Labhk**
**What does this PR do?**
Search Image by drag & drop : provide option to upload a photo and then search for more photos that are related to uploaded

**Related Issue(s)**
#37 

**Changes**
- Added toggle tabs "Keywords" and "Drag & Drop"
- Drag & Drop Component added
- Added Clarifai API for image classification

**Screenshots or GIFs (if applicable)**
Iimage
image

**Checklist**
- [ ] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [ ] My code follows the project's coding style and conventions.

**Additional Comments**
- U have to add following environment variables  to netlify
`REACT_APP_CLARIFAI_USER_ID =""`
`REACT_APP_CLARIFAI_APP_ID =""`
`REACT_APP_CLARIFAI_PAT =""`
https://docs.clarifai.com/api-guide/predict/images/

**By submitting this PR, I confirm that:**
- [ ] I have reviewed my code and believe it is ready for merging.
- [ ] I understand that this PR may be subject to review and changes.
- [ ] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Labhk** [comment]
should I resolve the conflict??

**Comment by Vijaykv5** [comment]
> should I resolve the conflict??

Yes!

**Comment by Vijaykv5** [comment]
Also I didn't find the API key as per the link you've given

**Comment by Labhk** [comment]
> Also I didn't find the API key as per the link you've given

you have to signup on and create application
  https://docs.clarifai.com/clarifai-basics/applications/create-an-application
  add APP_ID & USER_ID from this
  
 https://docs.clarifai.com/clarifai-basics/authentication/personal-access-tokens
 get PAT from this

**Comment by Labhk** [comment]
@Vijaykv5  do I need to anything else in this PR

**Review by juninhokaponne — APPROVED** [review]

**Pull request closed without merging**
