### PR TITLE
Added responsive footer with animation

### PR DESCRIPTION
**Pull request by SumanKisku**
**What does this PR do?**
This PR will fix PR #166 

**Changes**
Added footer with animation and fully responsive. But had to remove the rectangle.png.

**Screenshots or GIFs (if applicable)**
If your PR includes visual changes, provide screenshots or GIFs to demonstrate the changes.
[Screencast from 2023-10-29 18-44-51.webm](https://github.com/Vijaykv5/SnapGrid/assets/7936345/451cc4d5-220d-4a9d-82f8-4e4c00e850f1)

**Checklist**
- [ ] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [X] My code follows the project's coding style and conventions.
- [ ] I have added unit tests (if applicable) to ensure the code works as expected.
- [ ] I have updated the project documentation (if necessary).

**Additional Comments**
Add any additional comments, context, or information about this PR.

**By submitting this PR, I confirm that:**
- [X] I have reviewed my code and believe it is ready for merging.
- [X] I understand that this PR may be subject to review and changes.
- [ ] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by SumanKisku** [comment]
@Vijaykv5 hey please check this PR.

**Comment by Vijaykv5** [comment]
Thanks for your contribution @SumanKisku 
If you find this project helpful, please consider giving it a star ⭐️.
It helps to support the project and let others discover it too!

**Comment by SumanKisku** [comment]
Welcome already started 🌟

**Comment by Bisalkumar1** [comment]
I can make license,documentation font bold and make some animation to button

**Pull request merged**
