### PR TITLE
INFINITE SCROLL FEATURE ADDED

### LINKED ISSUE #59: INFINITE SCROLL
**Description**

Implement an infinite scroll feature that enables users to continuously load and browse more image results without the need for manual pagination. This feature enhances the user experience by providing seamless access to a large number of images.

**Expected Behavior**

When user reaches end of screen automatically more images will load.

**Actual Behavior**

User have to click on next and previous button to navigate pages.

Please assign this issue to me. I want to work on this issue.

### PR DESCRIPTION
**Pull request by Roar022**
**What does this PR do?**
Implementation of infinite scroll feature that enables users to continuously load and browse more image results without the need for manual pagination. This feature enhances the user experience by providing seamless access to a large number of images.

**Related Issue(s)**
## RESOLVES #59

**Changes**
Remove next and previous button. Now user can seamlessly get photos. More finite number of photos will reload when the user reaches at the end of page.

**Screenshots or GIFs (if applicable)**

**Checklist**
- [x] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [x] My code follows the project's coding style and conventions.
- [x] I have added unit tests (if applicable) to ensure the code works as expected.
- [x] I have updated the project documentation (if necessary).

**Additional Comments**

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Vijaykv5** [comment]
Please add a video too for checking on @Roar022

**Comment by Roar022** [comment]
# Demo
[Screencast_20231004_005635.webm](https://github.com/Vijaykv5/SnapGrid/assets/111555339/798994ad-bb3b-43aa-9467-f2412c07ba5b)

**Review by juninhokaponne — CHANGES_REQUESTED** [review]
I think it's a good feature, but it worries me about performance because you configure a call that with each new scroll will make a new request, thus rerendering the DOM.

If you want do this more performatic, you should consider that nexts steps.

1.  Use the new Suspense feature to handle component hydration, https://react.dev/reference/react/Suspense. It's important because there are a lot of renders in the app, like the one where there are a lot of photos to load.
2.  Instead of creating a handleInfiniteScroll variable, you can do this with a hook, useCallback, useCallback will work better with data caching to avoid re-rendering, read this article in the official documentation https://react.dev/reference/react/useCallback.

**Comment by Roar022** [comment]
> I think it's a good feature, but it worries me about performance because you configure a call that with each new scroll will make a new request, thus rerendering the DOM.
> 
> If you want do this more performatic, you should consider that nexts steps.
> 
> 1. Use the new Suspense feature to handle component hydration, https://react.dev/reference/react/Suspense. It's important because there are a lot of renders in the app, like the one where there are a lot of photos to load.
> 2. Instead of creating a handleInfiniteScroll variable, you can do this with a hook, useCallback, useCallback will work better with data caching to avoid re-rendering, read this article in the official documentation https://react.dev/reference/react/useCallback.

Thanks @juninhokaponne for your advice, I will look into it.

**Review by juninhokaponne — APPROVED** [review]

**Pull request closed without merging**
