### PR TITLE
made selection menu responsive for every device.

### PR DESCRIPTION
**Pull request by XxPython28xX**
**What does this PR do?**
the selection menu was not responsive for small devices, therefore made it fully responsive.

**Related Issue(s)**
#121

**Changes**
added flex-wrap to the menu div and my-2 to the buttons also fixed justify-center for every device.

**Screenshots or GIFs (if applicable)**
image

**Checklist**
- [x] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [x] My code follows the project's coding style and conventions.
- [x] I have added unit tests (if applicable) to ensure the code works as expected.
- [x] I have updated the project documentation (if necessary).

**Additional Comments**
Add any additional comments, context, or information about this PR.

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by XxPython28xX** [comment]
please review my changes are correct.

**Review by juninhokaponne — APPROVED** [review]

**Comment by Vijaykv5** [comment]
It should be like slider the  topic list @XxPython28xX

**Comment by XxPython28xX** [comment]
@Vijaykv5 
Understood 
I will do the slider thing , but can you please first merge this pull request with the label hacktober-accepted 😁.....
It would be highly appreciated😊....
After that I will definitely try the slider thing ..

**Comment by XxPython28xX** [comment]
As it did solve the problem in a way for now....

**Comment by Vijaykv5** [comment]
No @XxPython28xX We maintain a good UI .. The PR you've done is of crowded buttons and I don't want that 

Take your time and this will be always marked for hacktoberfest

**Pull request closed without merging**
