### PR TITLE
Thecodereule patch 1

### PR DESCRIPTION
**Pull request by thecodereule**
recommit of my last PR for issue #92 
In my last PR I left the  
"dev": true,
"requires": {}

which is an NPM configuration of a development build. so I removed it and made a new PR

### CODE REVIEW

**Review by thecodereule — COMMENTED** [review]
patched

**Comment by Vijaykv5** [comment]
Yes @thecodereule 
I don't see why this PR is for ?

Please add the Description or else it would be closed.

**Comment by thecodereule** [comment]
> What is that? and why was this line of code added? .
> 
> I think you need to describe it in the PR description.

In my last PR I left the  
"dev": true,
"requires": {}

which is an NPM configuration of a development build. so I removed it and made a new PR

**Comment by thecodereule** [comment]
recommit of my last PR for issue https://github.com/Vijaykv5/SnapGrid/issues/92
In my last PR I left the
"dev": true,
"requires": {}

which is an NPM configuration of a development build. so I removed it and made a new PR

**Pull request closed without merging**
