### PR TITLE
[Feature] Added Shimmer Loading to images card

### PR DESCRIPTION
**Pull request by veerprakash28**
**What does this PR do?**
Added Shimmer UI for Banner and Images Card

**Related Issue(s)**
Related Issue: https://github.com/Vijaykv5/Image-Searcher/issues/43

**Changes**
- Added Shimmer Loading Component for Image card and Banner
- Prettify Code
- Removed Extra Download function code
- Also changed the size of banner so that images card will appear perfectly

**Screenshots or GIFs (if applicable)**

Screenshot 2023-10-01 at 1 12 53 PM

### CODE REVIEW

**Comment by Vijaykv5** [comment]
It should not load at first. only load when api is called and something renders on screen.

**Comment by veerprakash28** [comment]
Yes, the loading will only happen when the API is called and till the data is not fetched

**Comment by Vijaykv5** [comment]
but as per the screenshot attached, it should not load right. Only once user types in , Shimmer Reflects into the UI

**Comment by veerprakash28** [comment]
Fixed that, now it will only load when someone searches

**Comment by veerprakash28** [comment]
https://github.com/Vijaykv5/Image-Searcher/assets/94482800/4cf14942-7bd0-4da0-9aa3-70995bd44856



This is how it will look

**Comment by veerprakash28** [comment]
Hi, any updates on the PR? @Vijaykv5

**Comment by Vijaykv5** [comment]
@veerprakash28 Some issues in ui

**Comment by veerprakash28** [comment]
is the live site link changed?

**Comment by Vijaykv5** [comment]
Yesh the banner changed and lot more

**Comment by Vijaykv5** [comment]
> can you share the live site link? from the readme file it's not accessible It will help in keeping up with the current flow @Vijaykv5

https://snapgrid.netlify.app/

**Comment by Vijaykv5** [comment]
> can you share the live site link? from the readme file it's not accessible It will help in keeping up with the current flow @Vijaykv5

Yeah I forget to change in readme ..Thanks for noticing it 
Its updated in description of this repo

**Comment by veerprakash28** [comment]
Added another PR #85 , please merge

**Comment by veerprakash28** [comment]
> > can you share the live site link? from the readme file it's not accessible It will help in keeping up with the current flow @Vijaykv5
> 
> Yeah I forget to change in readme ..Thanks for noticing it Its updated in description of this repo


On Live site, your API key is expired, it's giving error Rate Limit Exceeded

**Pull request merged**
