### PR TITLE
bugfixed: respinsive UI for small screeen devices and scroll button u…

### PR DESCRIPTION
**Pull request by aniimessh**
…pdated

**What does this PR do?**
This PR focuses on enhancing the user interface (UI) responsiveness and improving the overall user experience. It includes updates to the font style of the UI elements and the addition of a "Scroll Up" button for improved navigation.

**Related Issue(s)**
This PR is related to [Issue #31 ](https://github.com/Vijaykv5/Image-Searcher/issues/31), which discusses UI improvements and responsiveness enhancements.

**Changes**
Improved UI responsiveness for better display on various screen sizes and devices.
Updated the font style of UI elements for a more modern and consistent look.
Added a "Scroll Up" button to facilitate smooth navigation, allowing users to easily return to the top of the page with a single click.

**Screenshots or GIFs (if applicable)**
Mobile Screen
image
Tablet Screen
image
Desktop Screen
image

**Checklist**
- [x] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [x] My code follows the project's coding style and conventions.
- [x] I have added unit tests (if applicable) to ensure the code works as expected.
- [x] I have updated the project documentation (if necessary).

**Additional Comments**
The responsiveness improvements aim to provide a seamless experience for users across different devices and screen sizes. The updated font style ensures a more modern and visually appealing UI, aligning with the latest design standards. The "Scroll Up" button enhances navigation convenience, especially for lengthy pages.

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Vijaykv5** [comment]
the button to scroll up was already made in another PR, So no need to add it here

**Comment by Vijaykv5** [comment]
No update the changes and make commit

**Comment by aniimessh** [comment]
Done @Vijaykv5

**Comment by Vijaykv5** [comment]
May you can add a video of the current in locally , because I can see some issues while deployment

**Comment by aniimessh** [comment]
[Screencast from 10-01-2023 07:00:52 PM.webm](https://github.com/Vijaykv5/Image-Searcher/assets/97246133/936e3632-f62a-41c4-9b35-a1ad46ff38b5)
Here's the Video. please check and tell if there is any problem

**Comment by aniimessh** [comment]
whats the update @Vijaykv5

**Comment by aniimessh** [comment]
@Vijaykv5  check this now

**Comment by Vijaykv5** [comment]
Could add once again a video for the changes?
If everything in that is fine, I'll merge it

**Pull request closed without merging**
