### PR TITLE
enhanced the input search functionality, suggestions popups, keyword …

### PR DESCRIPTION
**Pull request by GeekkyCoder**
**Related Issue(s)**

 This pull request makes the input more dynamic than before, suggestions for users has been added as they type through 
 the  input box, it shows/lists the possible keywords that user can use, thus avoiding the headache for users to type a full 
 keyword.
 
 it also displays no options if a user type something that does not exist, possible implementation for asynchronous actions to dynamically populate predefined keywords from database, and to show a loading indicator till the keywords get fetched from db.

**Changes**
1) added functionality for dynamic input typing
2) keywords popups/suggestions as use keeps typing
3) validation if a user look for something that does not exist!

**Screenshots**
Screenshot (463)
Screenshot (464)
Screenshot (465)

**Checklist**
- [👍 ] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [👍 ] My code follows the project's coding style and conventions.
- [👍 ] I have added unit tests (if applicable) to ensure the code works as expected.
- [ 👍] I have updated the project documentation (if necessary).

**By submitting this PR, I confirm that:**
- [👍 ] I have reviewed my code and believe it is ready for merging.
- [ 👍] I understand that this PR may be subject to review and changes.
- [ 👍] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Vijaykv5** [comment]
@GeekkyCoder may you can add a video if possible implementing this feature. Also search for Key word like _"Circle"_

**Comment by GeekkyCoder** [comment]
sure here you go 

[SnapGrid.webm](https://github.com/Vijaykv5/SnapGrid/assets/104452510/9550156d-be61-4d94-ad95-6e6742f5a5f2)

**Comment by Vijaykv5** [comment]
@GeekkyCoder its only showing for the keywords right? I'm asking if we type _"circle"_ also I have some suggestions 
1. we don't want the suggesions to be Capitalized, everything in normal case.
2. Don't center the the suggestions.
3. I can see that there is a layout issue happening in the cards as per your video.
4. The suggestions should be available for all words not only for the given keywords

**Comment by GeekkyCoder** [comment]
updates: 

now the user can choose search for anything not only our pre defined keywords like before, if a keyword does not exist, user can add create their keywords and hit enter to search, if not found it shows the not found UI! 

[2023-10-09 00-11-57.webm](https://github.com/Vijaykv5/SnapGrid/assets/104452510/b263ba0b-55b4-4915-b61d-99539596e627)

suggestion are now in lowercase, later you can change the font size and might want to change font families according to your needs. 

i think its better to leave the suggestion center, this looks better than aligning them of right side or left side!

this is not a layout issue, when you open the dropdown, its basically points the user straight to dropdown to select any if he wants.

**Comment by Vijaykv5** [comment]
we don't need to create a keywords ....It should automatically suggest like you use in Youtube and all

**Comment by GeekkyCoder** [comment]
We are not creating them, if user type something that does not exist, it basically suggest him to choose this new keyword! I can remove the create from the suggestions, only show the user searched value!

**Comment by GeekkyCoder** [comment]
You must know that youtube uses AI as well!

**Comment by Vijaykv5** [comment]
if you may see the issue was completely on it.

or else what's the point in adding this feature

**Comment by GeekkyCoder** [comment]
I think it does what we expect, if you want to see some suggestions like YouTube, these giants use AI, the functionality is working, if the user type something that does not exist in our predefined keywords, user can choose their keyword and search for it! i dont have any experience with incorporating AI in any web app

**Pull request closed without merging**
