### PR TITLE
Updated Dark Mode UI Changes

### PR DESCRIPTION
**Pull request by Keshav-Aneja**
Updated the Dark Mode UI for the website.
1. Gave a Premium Outline Look for the Buttons
2. Added a glow effect on the search bar on being active
3. Special Styles for the selected Button in the dark mode.

Handled Issue #97

**Checklist**
- [X] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [X] My code follows the project's coding style and conventions.
- [X] I have added unit tests (if applicable) to ensure the code works as expected.
- [X] I have updated the project documentation (if necessary).

**By submitting this PR, I confirm that:**
- [X] I have reviewed my code and believe it is ready for merging.
- [X] I understand that this PR may be subject to review and changes.
- [X] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Keshav-Aneja** [comment]
[recording-2023-10-04-01-42-31.webm](https://github.com/Vijaykv5/SnapGrid/assets/119158790/0cf52b58-5d72-477e-b0b1-08cc5ce8b442)

**Comment by Keshav-Aneja** [comment]
@Vijaykv5  Please Review the PR

**Comment by Vijaykv5** [comment]
Please Resolve the conflicts @Roar022 After that I'll merge :)

**Comment by Vijaykv5** [comment]
Please resolve the conflicts @Keshav-Aneja

**Comment by Keshav-Aneja** [comment]
> Please resolve the conflicts @Keshav-Aneja

Ok I am checking for conflicts

**Pull request closed without merging**
